#!/bin/bash

ping -c 4 tesc.ucsd.edu
ping_exit_code=$?

if [ $ping_exit_code -eq 0 ]; then
    echo "Network connectivity to tesc.ucsd.edu is confirmed."
else
    echo "Network connectivity to tesc.ucsd.edu failed. Unable to proceed with file transfer."
fi
